version: '3.6'

services:

  # Kafka Service Running with Zookeeper
  kafka:
    image: spotify/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    command: >
        bash -c
        "(sleep 15s &&
        /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
        --create
        --zookeeper
        localhost:2181 --replication-factor 1 --partitions 1 --topic HAI &) && (supervisord -n)"
    healthcheck:
      test: ['CMD-SHELL', '/opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh --zookeeper localhost:2181 --list']
      interval: 20s
      timeout: 5s
      retries: 3
    networks:
      - hai-network
          
            # Jupyter Environment with PySpark
  pyspark:
    image: pyspark
    build: ./spark
    container_name: pyspark
    ports:
      - 8888:8888
    volumes:
      - ./data:/data
    #  - ./models:/models
      - ./transformers:/transformers
    networks:
      - hai-network

  # Framework for data visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: 
      - influxdb
    networks:
      - hai-network

  # Influx DB Server
  influxdb:
    image: bitnami/influxdb
    container_name: influxdb
    restart: always
    ports:
     - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER_BUCKET=${DEFAULT_BUCKET}
      - INFLUXDB_ADMIN_USER=${ADMIN_USERNAME}
      - INFLUXDB_ADMIN_USER_PASSWORD=${ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${AUTH_TOKEN}
    networks:
      - hai-network


 
  # Python Environement running a KafkaProducer programm
  producer:      
    image: producer
    container_name: producer
    build: ./kafka
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - hai-network


networks:
  hai-network:
    
volumes:
  grafana:
  influxdb:

